/**
 * SEO keyword list for Ranasi marketing pages.
 * Exactly 300 unique search phrases.
 */

export const SEO_KEYWORDS: string[] = [

  // Core autofill
  'autofill',
  'auto fill',
  'form filler',
  'form autofill',
  'web form autofill',
  'fill web forms',
  'fill forms automatically',
  'automatic form fill',
  'one click fill',
  'one-click form fill',
  'fill web forms with one click',
  'instant form fill',
  'smart form filler',
  'browser form autofill',
  'autofill forms online',
  'auto fill forms chrome',
  'fill out forms fast',
  'quick form fill',
  'bulk form fill',
  'multi field autofill',
  'address autofill',
  'email phone fill',
  'phone number autofill',
  'name email autofill',
  'contact form autofill',
  'checkout form autofill',
  'shipping address autofill',
  'billing address autofill',
  'job application form filler',
  'job application autofill',
  'resume form autofill',
  'registration form autofill',
  'signup form autofill',
  'survey form autofill',
  'online application autofill',
  'autofill personal info',
  'autofill contact details',
  'form auto complete',
  'autocomplete forms',
  'fill forms in seconds',
  'save time filling forms',
  'reuse form data',
  'stored form profiles',
  'autofill without typing',
  'click to fill forms',
  'paste form data',
  'form data templates',
  'custom form fields fill',
  'dynamic form autofill',
  'html form autofill',

  // Chrome extension
  'chrome autofill',
  'chrome autofill extension',
  'chrome form filler',
  'chrome form autofill',
  'best chrome autofill extension',
  'best chrome autofill extension 2026',
  'chrome extension autofill forms',
  'chrome web store autofill',
  'chrome web store form filler',
  'install chrome autofill extension',
  'browser extension autofill',
  'chrome extension form filler',
  'chromium autofill extension',
  'edge autofill extension',
  'chrome auto fill tool',
  'chrome fill forms extension',
  'chrome one click fill',
  'chrome address autofill extension',
  'chrome checkout autofill',
  'chrome job application filler',
  'chrome extension for forms',
  'form filler chrome extension',
  'auto fill chrome extension free',
  'chrome autofill alternative',
  'vs built-in chrome autofill',
  'better than chrome autofill',
  'enhance chrome autofill',
  'chrome autofill not working fix',
  'chrome form fill helper',
  'chrome extension pin websites',
  'chrome new tab extension',
  'chrome productivity extension',
  'chrome desktop extension',
  'lightweight chrome autofill',
  'privacy friendly chrome autofill',
  'offline chrome form filler',
  'chrome extension profiles',
  'chrome autofill extension review',
  'how to autofill forms in chrome',
  'chrome autofill multiple profiles',

  // AI fill
  'ai autofill',
  'ai form filler',
  'ai form autofill',
  'ai auto fill',
  'ai fill forms',
  'smart ai autofill',
  'ai powered form fill',
  'ai powered autofill extension',
  'intelligent form filler',
  'ai assisted form fill',
  'ai fill web forms',
  'machine learning form autofill',
  'context aware autofill',
  'smart field detection',
  'ai detect form fields',
  'ai map form fields',
  'adaptive form fill',
  'ai checkout autofill',
  'ai job application fill',
  'natural language form fill',
  'ai one click fill',
  'gpt form filler',
  'llm form autofill',
  'ai browser form assistant',
  'smart autofill 2026',
  'ai chrome autofill',
  'ai form completion',
  'predictive form fill',
  'ai field suggestions',
  'intelligent autofill chrome',

  // New tab
  'new tab desktop',
  'chrome new tab page',
  'custom new tab chrome',
  'new tab dashboard',
  'new tab start page',
  'pin websites new tab',
  'pin websites chrome',
  'pin favorite sites',
  'pinned websites desktop',
  'quick access new tab',
  'new tab shortcuts',
  'new tab bookmarks grid',
  'desktop new tab pins',
  'custom chrome start page',
  'replace chrome new tab',
  'productivity new tab',
  'minimal new tab chrome',
  'new tab with pinned sites',
  'browser new tab organizer',
  'new tab quick links',
  'favorite sites on new tab',
  'new tab workspace',
  'chrome homepage pins',
  'new tab speed dial',
  'visual bookmarks new tab',

  // Profiles
  'autofill profiles',
  'form fill profiles',
  'multiple autofill profiles',
  'switch autofill profiles',
  'profile based form fill',
  'password-less profile fill',
  'passwordless autofill',
  'profile fill without passwords',
  'personal info profiles',
  'work profile autofill',
  'personal profile autofill',
  'job seeker autofill profile',
  'shipping profile autofill',
  'billing profile fill',
  'create autofill profile',
  'manage form fill profiles',
  'named autofill profiles',
  'one click profile fill',
  'select profile to fill form',
  'multi identity form fill',
  'context profiles autofill',
  'saved identity profiles',
  'form profile templates',
  'profile data for forms',
  'secure profile fill',
  'local autofill profiles',
  'export autofill profiles',
  'import form profiles',
  'sync free profile fill',
  'device local profiles',

  // Pro/pricing
  'autofill extension pro',
  'pro form filler',
  'pro themes autofill',
  'premium chrome autofill',
  'autofill pro license',
  'license key autofill extension',
  'activate license key chrome extension',
  'pro unlock form filler',
  'paid autofill chrome extension',
  'lifetime license form filler',
  'autofill extension pricing',
  'upgrade to pro autofill',
  'pro chrome extension themes',
  'custom themes form filler',
  'dark theme autofill extension',
  'pro features form fill',
  'unlimited profiles pro',
  'pro pin websites themes',
  'license key activation',
  'buy pro autofill extension',
  'autofill extension subscription free alternative',
  'one time purchase form filler',
  'pro desktop new tab themes',
  'premium new tab chrome',
  'pro profile limits unlock',

  // Use cases
  'fill checkout forms faster',
  'ecommerce checkout autofill',
  'online shopping form fill',
  'fill shipping forms quickly',
  'apply to jobs faster',
  'job board form autofill',
  'linkedin application autofill',
  'ats form filler',
  'government form autofill',
  'school application autofill',
  'university application form fill',
  'insurance form autofill',
  'bank account open form fill',
  'kyc form autofill',
  'rental application autofill',
  'visa form autofill helper',
  'travel booking form fill',
  'hotel checkout autofill',
  'event registration autofill',
  'newsletter signup autofill',
  'crm lead form fill',
  'saas onboarding form fill',
  'demo request form autofill',
  'contact us form filler',
  'support ticket form fill',
  'tax form autofill helper',
  'medical intake form fill',
  'patient form autofill',
  'volunteer application autofill',
  'scholarship application form fill',
  'freelance client form fill',
  'invoice details autofill',
  'repeat order form fill',
  'multi site form templates',
  'fill same form many times',
  'speed run web forms',
  'reduce form fatigue',
  'accessibility form fill helper',
  'mobile chrome form autofill',
  'desktop chrome form productivity',
  'remote work form automation',
  'freelancer form filler tool',
  'student application autofill',
  'recruiter form fill speed',
  'hr onboarding form fill',

  // Thai queries
  'ส่วนขยาย chrome เติมฟอร์ม',
  'autofill chrome ภาษาไทย',
  'เติมฟอร์มอัตโนมัติ',
  'โปรแกรมเติมฟอร์ม',
  'ส่วนขยายเติมฟอร์ม',
  'เติมฟอร์มคลิกเดียว',
  'ai เติมฟอร์ม',
  'chrome autofill ไทย',
  'เติมที่อยู่ อัตโนมัติ',
  'เติมอีเมล เบอร์โทร อัตโนมัติ',
  'ฟอร์มสมัครงาน autofill',
  'เติมฟอร์ม checkout',
  'ส่วนขยาย chrome ใหม่',
  'new tab chrome ปักหมุดเว็บ',
  'ปักหมุดเว็บไซต์ chrome',
  'โปรไฟล์เติมฟอร์ม',
  'หลายโปรไฟล์ autofill',
  'license key ส่วนขยาย',
  'ธีม pro chrome extension',
  'เติมฟอร์มไม่ใช้รหัสผ่าน',
  'ฟอร์มสมัครสมาชิก อัตโนมัติ',
  'chrome web store เติมฟอร์ม',
  'เครื่องมือเติมฟอร์ม 2026',
  'autofill ดีกว่า chrome ในตัว',
  'เติมฟอร์มเร็ว chrome',
  'desktop new tab ไทย',
  'โปรไฟล์งาน autofill',
  'ที่อยู่จัดส่ง autofill',
  'ฟอร์มชำระเงิน เติมอัตโนมัติ',
  'ส่วนขยาย productivity chrome',
  'ai autofill ภาษาไทย',
  'ฟอร์มออนไลน์ เติมอัตโนมัติ',
  'extension เติมข้อมูลส่วนตัว',
  'ปักหมุดเว็บ new tab',
  'ซื้อ license autofill',
  'ธีมสวย chrome extension',
  'เติมฟอร์มสมัครเรียน',
  'เติมฟอร์มประกัน',
  'ฟอร์มราชการ autofill',
  'chrome เติมชื่อ ที่อยู่',
  'one click fill ไทย',
  'form filler chrome ไทย',
  'โปรไฟล์ส่วนตัว เติมฟอร์ม',
  'โปรไฟล์ที่ทำงาน autofill',
  'เครื่องมือช่วยกรอกฟอร์ม',
  'กรอกฟอร์มอัตโนมัติ chrome',
  'extension กรอกฟอร์ม',
  'autofill ที่อยู่ไทย',
  'เติมรหัสไปรษณีย์ อัตโนมัติ',
  'ฟอร์มจองโรงแรม autofill',
  'สมัครงานออนไลน์ เติมฟอร์ม',
  'checkout เร็วขึ้น chrome',
  'ส่วนขยายฟรี เติมฟอร์ม',
  'pro themes เติมฟอร์ม',
  'จัดการโปรไฟล์ autofill',
];

export const KEYWORD_COUNT = SEO_KEYWORDS.length;
